apiVersion: v2
name: sulfoxide-boron
description: Helm chart to deploy internal ingress controller with VPN access to internal services using cloudflared
type: application
version: 1.7.0
appVersion: "2023.10.0"
dependencies:
  - name: sulfoxide-bromine
    version: 1.2.3
    repository: oci://ghcr.io/atomicloud/sulfoxide.bromine
