serviceTree:
  landscape: suicune
  cluster: opal-ruby

# -- Create SecretStore via secret of secrets pattern
sulfoxide-bromine:
  serviceTree:
    landscape: suicune
    cluster: opal-ruby
  annotations:
    # -- Helm hook to run
    helm.sh/hook: pre-install,pre-upgrade
    # -- Helm weight to run
    helm.sh/weight: "-5"


# -- Secret Annotations (External Secrets) to control synchronization
secretAnnotation:
  # -- Helm hook to run
  helm.sh/hook: pre-install,pre-upgrade
  # -- Helm weight to run
  helm.sh/weight: "-4"

auth:
  internal:
    enable: false
  external:
    enable: true
    refreshInterval: 1h
    remoteSecretName: OPAL_RUBY_INGRESS_TOKEN

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi