# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  platform: &platform sulfoxide
  service: &service boron
  module: tunnel
  layer: "1"

# -- Create SecretStore via secret of secrets pattern
sulfoxide-bromine:
  serviceTree:
    platform: *platform
    service: *service
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  # -- Store name to create
  storeName: *service
  # -- Secret of Secrets reference
  rootSecret:
    name: *service
    # -- DOPPLER Token Reference
    ref:
      clientId: SULFOXIDE_BORON_CLIENT_ID
      clientSecret: SULFOXIDE_BORON_CLIENT_SECRET


# -- Secret Annotations (External Secrets) to control synchronization
secretAnnotation:
  argocd.argoproj.io/sync-wave: "-2"

# -- Cloudflare Tunnel Token
auth:

  # -- Secret Name that stores the Token with key TUNNEL_TOKEN
  secretName: cloudflare-tunnel-token

  # -- Secret directly inlined in value files
  internal:
    # -- Use hard coded secret
    enable: false

    # -- Hard coded Cloudflare token
    token: ""

  # -- Use external secret
  external:

    # -- Enable the use of external secret
    enable: true

    # -- Refresh Rate
    refreshInterval: 1h

    # -- Remote Secret Reference name
    remoteSecretName: INGRESS_TOKEN

    # Secret Store to reference
    secretStore:
      # -- Name of the Secret Store
      name: *service

      # -- Kind of the Secret Store: `ClusterSecretStore` or `SecretStore`
      kind: SecretStore

    # -- Secret policy
    policy:
      # -- Creation policy
      creation: Owner

      # -- Deletion policy
      deletion: Retain

# -- Number of Replicas, only if HPA is not enabled
replicaCount: 1

# -- Auto-scaling
autoscaling:
  # -- Enable or disable auto-scaling
  enabled: true

  # minimum number of replicas during auto-scaling
  minReplicas: 1

  # maximum number of replicas during auto-scaling
  maxReplicas: 3

  # -- Target CPU Utilization
  targetCPUUtilizationPercentage: 80
  # -- Target Memory Utilization
  targetMemoryUtilizationPercentage: 80

# -- Image configurations
image:
  repository: "cloudflare/cloudflared"
  pullPolicy: IfNotPresent


config:
  # -- target kubernetes cluster IP family. 4 or 6
  clusterIpVersion: 4

  # -- Ports which cloudflared listen to metrics on
  metricPort: 2000


# -- Image pull secrets
imagePullSecrets: [ ]

# -- Override name ( will change only the chart name)
nameOverride: ""

# -- Additional Annotations to add to pods
podAnnotations: { }

# -- Security Context for Pods
podSecurityContext: { }

# -- Generate security Context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10000
# -- resource limits
resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 15m
    memory: 128Mi

# -- node selectors
nodeSelector: { }

# -- toleration
tolerations: [ ]

# -- affinity
affinity: { }
