serviceTree:
  landscape: entei
  cluster: topaz

auth:
  internal:
    enable: false

  external:
    enable: true
    refreshInterval: 1h
    remoteSecretName: TOPAZ_AMBER_INGRESS_TOKEN

sulfoxide-bromine:
  serviceTree:
    landscape: entei
    cluster: topaz

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 15m
    memory: 128Mi