serviceTree:
  landscape: suicune
  cluster: opal

auth:
  internal:
    enable: false

  external:
    enable: true
    refreshInterval: 1h
    remoteSecretName: INGRESS_TOKEN

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 15m
    memory: 128Mi