version: "3"

env:
  RELEASE_NAME: sulfoxide-boron

includes:
  pichu:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pichu
      CLUSTER: opal
  suicune:opal-ruby:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: suicune
      CLUSTER: opal-ruby

tasks:
  # Utility
  start:cluster:
    desc: Starts the playground cluster to test helm charts
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  stop:cluster:
    desc: Destroys the playground cluster to test helm charts
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh

  # Helm Operations
  update:
    desc: Update Helm dependencies
    dir: chart
    cmds:
      - helm dependency update

  latest:
    desc: Get the latest version of Cloudflared
    cmds:
      - >-
        echo "cloudflared: $(skopeo list-tags docker://docker.io/cloudflare/cloudflared | jq -r '.Tags[]' | sort -V | tail -n 6 | head -n 1)"
      - >-
        echo "sulfoxide-bromine: $(skopeo list-tags docker://ghcr.io/atomicloud/sulfoxide.bromine/sulfoxide-bromine | jq -r '.Tags[]' | sort -V | tail -n 1)"
