{{- if .Values.auth.external.enable }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name -}}-external-secret
  annotations:
   {{- include "atomi-internal-ingress.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
  labels:
    {{- include "atomi-internal-ingress.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.auth.external.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.auth.external.secretStore.name }}
    kind: {{ .Values.auth.external.secretStore.kind }}
  target:
    name: {{ .Values.auth.secretName }}
    creationPolicy: {{ .Values.auth.external.policy.creation }}
    deletionPolicy: {{ .Values.auth.external.policy.deletion }}
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: "{{ .Values.auth.external.remoteSecretName }}"
{{- end }}
