{{- if .Values.auth.internal.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  annotations:
     {{- include "atomi-internal-ingress.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
  labels:
    {{- include "atomi-internal-ingress.labels" . | nindent 4 }}
data:
  TUNNEL_TOKEN: {{ b64enc .Values.auth.internal.token }}
{{- end }}
